CREATE TABLE IF NOT EXISTS products (
 id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT DEFAULT '',
 price INTEGER NOT NULL,compare_price INTEGER,category TEXT DEFAULT 'T-Shirts',featured INTEGER DEFAULT 0,
 active INTEGER DEFAULT 1,image_url TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS variants (
 id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,color TEXT NOT NULL,size TEXT NOT NULL,
 sku TEXT NOT NULL UNIQUE,stock INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS orders (
 id INTEGER PRIMARY KEY AUTOINCREMENT,customer_name TEXT NOT NULL,phone TEXT NOT NULL,city TEXT NOT NULL,address TEXT NOT NULL,
 notes TEXT DEFAULT '',subtotal INTEGER NOT NULL,shipping INTEGER NOT NULL,total INTEGER NOT NULL,
 payment_method TEXT NOT NULL DEFAULT 'cod',payment_status TEXT NOT NULL DEFAULT 'pending',
 order_status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS order_items (
 id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,product_id INTEGER NOT NULL,variant_id INTEGER,
 quantity INTEGER NOT NULL,price INTEGER NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
);